<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <?php if (!empty($_SESSION['message'])) { ?>
                <div class="alert alert-success" role="alert">
                    <?= $_SESSION['message'] ?>
                </div>
            <?php } ?>

            <div class="card">
                <div class="card-header">
                    All posts
                </div>
                <div class="card-body">
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <td>ID</td>
                            <td>Title</td>
                            <td>Author</td>
                            <td>Created At</td>
                            <td class="text-center" style="width: 140px">Actions</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if (!empty($this->view->posts->getItems())) { ?>
                            <?php foreach ($this->view->posts->getItems() as $post) { ?>
                                <tr>
                                    <td><?= $post->id ?></td>
                                    <td><?= $post->title ?></td>
                                    <td><?= $post->author->name ?></td>
                                    <td><?= $post->created_at ?></td>
                                    <td>
                                        <a href="/admin/posts/<?= $post->slug ?>" class="btn btn-sm btn-info">
                                            Edit
                                        </a>
                                        <a href="/admin/posts/<?= $post->slug ?>/delete" class="btn btn-sm btn-danger">
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td colspan="5" class="text-center">
                                    No entries found.
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <nav aria-label="...">
                        <ul class="pagination d-flex justify-content-between mb-0">
                            <li class="page-item <?= $this->view->posts->getCurrentPage() === 1 ? 'disabled' : '' ?>">
                                <a class="page-link" href="/admin/posts?page=<?= $this->view->posts->previousPage() ?>" tabindex="-1" aria-disabled="true">Previous</a>
                            </li>
                            <li class="page-item <?= $this->view->posts->hasMorePages() ? '' : 'disabled' ?>">
                                <a class="page-link" href="/admin/posts?page=<?= $this->view->posts->nextPage() ?>">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>